Add enable and disable batch actions
owncloud/ocis-accounts pull request #109
Opened 2020-09-02 18:31 UTC by LukasHirt

2020-09-02 18:33 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-06 19:40 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-06 19:46 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 08:17 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 08:26 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 08:53 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 09:03 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 09:12 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 09:33 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 09:45 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 11:54 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 12:30 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 12:31 UTC, kulmann requested changes
Things I noticed in the UI:
- we should add a `clear selection` link like in the files app
- when you select all users, switch to the files app and come back to the accounts app, the selection of the rows is cleared, but the `select all` checkbox is still checked and the bulk action row (`6 selected users` and the actions dropdown) is still visible. One funny thing about this: if you select one more user (which is possible because the checkboxes are not checked), the bulk action row goes to 7 selected users, while we only have 6, and the `select all` checkbox is unchecked (because the selection doesn't equal the overall number of users anymore)

Also, see comments :-)
Most of the code looks really good already, thank you!

2020-09-07 12:31 UTC, kulmann commented on ui/components/App.vue
> +              <oc-icon name="expand_more" />
Can we flip the icon into the other direction (= use the `expand_less` icon) when the drop is expanded? Only if it's easy to achieve.

2020-09-07 12:31 UTC, kulmann commented on ui/components/App.vue
> +                <oc-button
oc-button needs an `ariaLabel` right?

2020-09-07 12:31 UTC, kulmann commented on ui/components/App.vue
> +    selectedAccountsAmount () {
What do you think of `numberOfSelectedAccounts` or `selectedAccountsCount` as var name?

2020-09-07 12:31 UTC, kulmann commented on ui/components/App.vue
> +      const isAnyAccountDisabled = this.selectedAccounts.some(account => !account.accountEnabled)
If you'd count the number of disabled accounts you would iterate only once and then compare numbers (`number of disabled accounts > 0` and `number of disabled accounts < total number of accounts`).

2020-09-07 12:31 UTC, kulmann commented on ui/components/accounts/AccountsList.vue
> +    toggleAllAccountsSelection () {
I don't see a reason for introducing a wrapping function. Could call the `toggleSelectionAll` directly on `@change` in the template. Please clarify if needed.

2020-09-07 12:31 UTC, kulmann commented on ui/store/index.js
> +    getters.areAllAccountsSelected ? commit('SET_SELECTED_ACCOUNTS', []) : commit('SET_SELECTED_ACCOUNTS', [...state.accounts])
You can re-use `RESET_ACCOUNTS_SELECTION` when all accounts are selected

2020-09-07 12:31 UTC, kulmann commented on ui/store/index.js
> +  async enableAccounts ({ commit, dispatch, state, rootGetters }) {
Please refactor the function body of this and `disableAccounts` into one generic function. :-) still good to have dedicated functions for `enableAccounts` and `disableAccounts`, but they should call one generic function doing the heavy lifting.

2020-09-07 12:38 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 13:01 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         

Clones added
============
- ui/store/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 15:51 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- ui/tests/acceptance/pageobjects/accountsPage.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-accounts/pullRequest?prid=6113746&bid=20008915)

2020-09-07 15:56 UTC, kulmann approved these changes
🚀

2020-09-07 16:09 UTC, merged